create table market_regimes(id uuid primary key default gen_random_uuid(),regime text not null,risk_multiplier numeric not null,payload jsonb not null,observed_at timestamptz not null,created_at timestamptz not null default now());
create table theses(id uuid primary key default gen_random_uuid(),symbol text not null,thesis_type text not null,score numeric not null,confidence numeric not null,payload jsonb not null,source_content text not null,source_quality jsonb not null,market_regime text not null,created_at timestamptz not null default now());
create table thesis_assumptions(id uuid primary key default gen_random_uuid(),thesis_id uuid not null references theses(id) on delete cascade,kind text not null,value text not null);
create table price_reflections(id uuid primary key default gen_random_uuid(),thesis_id uuid not null references theses(id),symbol text not null,payload jsonb not null,created_at timestamptz not null default now());
create table entry_plans(id uuid primary key default gen_random_uuid(),thesis_id uuid not null references theses(id),symbol text not null,payload jsonb not null,created_at timestamptz not null default now());
create table trade_evaluations(id uuid primary key default gen_random_uuid(),trade_id uuid not null unique references trades(id),outcome_type text not null,payload jsonb not null,created_at timestamptz not null default now());
create table risk_events(id uuid primary key default gen_random_uuid(),event_type text not null,severity text not null,payload jsonb not null,created_at timestamptz not null default now());
alter table market_regimes enable row level security;alter table theses enable row level security;alter table thesis_assumptions enable row level security;alter table price_reflections enable row level security;alter table entry_plans enable row level security;alter table trade_evaluations enable row level security;alter table risk_events enable row level security;
update strategy_versions set version=3,status='paper',config='{"minThesisScore":8.5,"minRelativeVolume":5,"maxSpreadPercent":2,"maxPremarketGapPercent":80,"maxRiskPerTradePercent":0.25,"maxDailyLossPercent":1,"maxWeeklyLossPercent":3}' where id='00000000-0000-0000-0000-000000000001';
