import { StyleSheet } from 'react-native';
import { colors as C } from './theme';

export const styles = StyleSheet.create({
  fill: { flex: 1 },
  safe: { flex: 1, backgroundColor: C.sky },
  shell: { flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center', backgroundColor: C.background, borderLeftWidth: StyleSheet.hairlineWidth, borderRightWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  screenDrawer: { position: 'absolute', top: 72, left: 0, right: 0, bottom: 0, borderTopLeftRadius: 26, borderTopRightRadius: 26, overflow: 'hidden', backgroundColor: C.background, boxShadow: '0 -4px 18px rgba(53,74,82,.12)', elevation: 8 },
  header: { minHeight: 68, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.header, borderBottomColor: '#C6DDE7', borderBottomWidth: 1 },
  brand: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6 },
  brandText: { fontSize: 22, letterSpacing: -1, color: C.ink, fontWeight: '800' },
  brandEnglish: { fontSize: 12, color: C.primary, marginLeft: 3 },
  headerTitle: { flex: 1, color: C.ink, fontSize: 16, fontWeight: '700' },
  labBadge: { fontSize: 10, color: C.primary, backgroundColor: '#F4FAFD', borderRadius: 7, paddingHorizontal: 7, paddingVertical: 6 },
  backButton: { width: 44, minHeight: 44, justifyContent: 'center' },
  back: { fontSize: 25, color: C.ink },
  content: { paddingHorizontal: 22, paddingBottom: 28 },
  homeContent: { paddingHorizontal: 0, paddingBottom: 0 },
  welcome: { backgroundColor: C.sky, padding: 22, paddingTop: 25, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: C.line },
  welcomeText: { flex: 1 },
  welcomeDooji: { marginLeft: 2, alignSelf: 'flex-end', marginBottom: 10 },
  eyebrow: { fontSize: 12, color: C.primary, marginBottom: 10 },
  heroTitle: { fontSize: 25, lineHeight: 35, fontWeight: '700', letterSpacing: -.9, color: C.ink },
  heroDescription: { fontSize: 12, lineHeight: 20, color: C.muted, marginTop: 10 },
  quickCompose: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 20, paddingVertical: 19, backgroundColor: C.paper, borderBottomWidth: 1, borderBottomColor: C.line },
  avatar: { width: 46, height: 46, backgroundColor: C.sky, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  avatarPeach: { backgroundColor: '#FBECE4' },
  composePrompt: { fontSize: 15, color: C.ink },
  composeHint: { fontSize: 11, color: C.muted, marginTop: 7 },
  composeAction: { color: '#FFFFFF', backgroundColor: C.primary, paddingHorizontal: 12, paddingVertical: 11, borderRadius: 9, fontSize: 13, fontWeight: '600' },
  doojiNote: { margin: 18, marginBottom: 8, padding: 13, borderRadius: 10, backgroundColor: C.butter, gap: 5 },
  doojiName: { color: C.accent, fontSize: 11, fontWeight: '700' },
  doojiText: { color: C.ink, fontSize: 13, lineHeight: 21 },
  timelineHeading: { paddingHorizontal: 20, paddingTop: 19, paddingBottom: 7, flexDirection: 'row', alignItems: 'center', gap: 8 },
  timelineTitle: { color: C.ink, fontSize: 16, fontWeight: '700' },
  count: { fontSize: 12, color: C.muted },
  filterRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: C.line, paddingHorizontal: 12 },
  filter: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  filterSelected: { borderBottomColor: C.primary },
  filterText: { fontSize: 12, color: C.muted },
  filterTextSelected: { color: C.primary, fontWeight: '700' },
  button: { backgroundColor: C.primary, borderRadius: 11, minHeight: 52, paddingVertical: 15, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' },
  buttonText: { fontSize: 15, color: '#FFFFFF', fontWeight: '600' },
  buttonSecondary: { backgroundColor: C.pale },
  disabled: { opacity: .48 }, pressed: { opacity: .72 },
  sectionLabel: { fontSize: 14, fontWeight: '700', color: C.ink, marginTop: 25, marginBottom: 12 },
  listHeader: { flexDirection: 'row', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' },
  empty: { alignItems: 'center', paddingHorizontal: 24, paddingVertical: 30, gap: 6 },
  emptyTitle: { color: C.ink, fontSize: 16, fontWeight: '600', marginTop: 5 },
  emptyText: { color: C.muted, fontSize: 13, lineHeight: 21, textAlign: 'center', marginTop: 4 },
  emptyAction: { minHeight: 44, padding: 12, justifyContent: 'center' },
  linkText: { color: C.primary, fontSize: 13, fontWeight: '600' },
  timelineFootnote: { padding: 20, borderTopWidth: 1, borderTopColor: C.line, gap: 5 },
  footer: { textAlign: 'center', color: C.muted, fontSize: 11, lineHeight: 18 },
  bottomBar: { minHeight: 68, flexDirection: 'row', borderTopWidth: 1, borderTopColor: C.line, backgroundColor: C.paper },
  bottomItem: { flex: 1, minHeight: 64, paddingVertical: 8, alignItems: 'center', justifyContent: 'center', gap: 4 },
  bottomIcon: { fontSize: 23, color: C.muted, lineHeight: 27 },
  bottomLabel: { fontSize: 11, color: C.muted },
  navActive: { color: C.primary, fontWeight: '700' },
  capsuleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 11, borderBottomWidth: 1, borderBottomColor: C.line, paddingHorizontal: 18, paddingVertical: 20, backgroundColor: C.paper },
  rowMain: { flex: 1 },
  byline: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  author: { color: C.ink, fontSize: 13, fontWeight: '700' },
  handle: { color: C.muted, fontSize: 11 },
  rowDate: { color: C.muted, fontSize: 11, marginLeft: 'auto' },
  rowTitle: { fontSize: 16, lineHeight: 25, fontWeight: '600', color: C.ink, marginTop: 9 },
  rowCaption: { fontSize: 12, lineHeight: 20, color: C.muted, marginTop: 7 },
  attachmentRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap', marginTop: 10 },
  attachment: { fontSize: 10, color: C.muted, backgroundColor: '#F3F6F7', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 5 },
  rowFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap', marginTop: 14 },
  statusPill: { fontSize: 11, lineHeight: 18, color: C.primary, backgroundColor: C.sky, paddingHorizontal: 9, paddingVertical: 4, borderRadius: 7 },
  readyPill: { backgroundColor: C.butter, color: '#79582E' },
  openedPill: { backgroundColor: '#FBECE4', color: C.accent },
  rowLink: { color: C.primary, fontSize: 11 },
  pageEyebrow: { fontSize: 12, color: C.primary, marginTop: 28, marginBottom: 10 },
  pageTitle: { fontSize: 26, lineHeight: 37, letterSpacing: -.9, color: C.ink, fontWeight: '700' },
  description: { color: C.muted, fontSize: 14, lineHeight: 23, marginTop: 12, marginBottom: 6 },
  input: { backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 10, padding: 14, color: C.ink, fontSize: 15, minHeight: 50 },
  letterInput: { height: 150, lineHeight: 25, backgroundColor: '#FFFEF5' },
  optional: { marginLeft: 'auto', fontSize: 11, color: C.muted },
  photoPicker: { borderWidth: 1, borderColor: '#C2D9E2', borderStyle: 'dashed', borderRadius: 12, backgroundColor: C.pale, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 8 },
  photoPlus: { fontSize: 26, color: C.primary }, photoLabel: { fontSize: 14, color: C.primary },
  photoFrame: { borderRadius: 12, overflow: 'hidden' }, photoPreview: { width: '100%', height: 190 },
  removePhoto: { position: 'absolute', right: 8, top: 8, width: 44, height: 44, borderRadius: 22, backgroundColor: C.paper, alignItems: 'center', justifyContent: 'center' }, removePhotoText: { color: C.ink },
  fieldHint: { color: C.muted, fontSize: 12, lineHeight: 20, marginTop: 9, marginBottom: 3 },
  testTag: { marginLeft: 'auto', color: C.accent, fontSize: 10 },
  durationRow: { flexDirection: 'row', gap: 6 },
  duration: { flex: 1, alignItems: 'center', minHeight: 46, justifyContent: 'center', borderWidth: 1, borderColor: C.line, borderRadius: 9 },
  durationSelected: { backgroundColor: C.primary, borderColor: C.primary },
  durationText: { color: C.muted, fontSize: 12 }, durationTextSelected: { color: '#FFFFFF', fontWeight: '600' },
  note: { backgroundColor: C.pale, borderRadius: 12, padding: 16, marginVertical: 18 },
  noteText: { fontSize: 13, lineHeight: 22, color: C.muted },
  webNote: { color: C.muted, fontSize: 12, textAlign: 'center', lineHeight: 20, marginTop: 14, marginBottom: 10 },
  errorBox: { marginTop: 16, marginHorizontal: 4, backgroundColor: C.errorBackground, padding: 16, borderRadius: 12 },
  errorText: { fontSize: 13, color: C.error, lineHeight: 21 }, retry: { color: C.error, fontSize: 13, textDecorationLine: 'underline', paddingVertical: 12 },
  success: { backgroundColor: C.sky, borderRadius: 12, padding: 16, marginVertical: 16 },
  successText: { color: C.primary, fontSize: 13, lineHeight: 22 },
  sealedArt: { alignItems: 'center', paddingVertical: 18 },
  sealedBadge: { fontSize: 13, color: C.primary, backgroundColor: C.sky, paddingVertical: 9, paddingHorizontal: 16, borderRadius: 10 },
  details: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: C.line, paddingVertical: 18, gap: 16 },
  detailLine: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  detailKey: { fontSize: 12, color: C.muted }, detailValue: { fontSize: 13, color: C.ink, flexShrink: 1, textAlign: 'right' },
  openedPhoto: { width: '100%', height: 280, borderRadius: 16, marginTop: 22, backgroundColor: C.pale },
  letterPaper: { backgroundColor: '#FFFDF1', borderWidth: 1, borderColor: '#EAE3CA', borderRadius: 16, marginTop: 22, padding: 24 },
  letterTitle: { fontSize: 17, fontWeight: '600', color: C.ink, marginBottom: 22 },
  letterBody: { fontSize: 16, lineHeight: 30, color: C.ink },
  letterSignature: { color: C.accent, fontSize: 12, marginTop: 30, textAlign: 'right' },
  labPanel: { borderBottomWidth: 1, borderBottomColor: C.line, paddingVertical: 22, gap: 12 },
  labTitle: { fontSize: 14, fontWeight: '700', color: C.primary },
  labValue: { fontSize: 18, color: C.ink, letterSpacing: -.5 }, endpoint: { fontSize: 12, color: C.muted },
  labBody: { fontSize: 14, color: C.muted, lineHeight: 27 },
  mediaPanel: { marginBottom: 12, gap: 4 }, mediaMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  removeMedia: { color: C.accent, fontSize: 12, paddingVertical: 14 },
});
