import{z}from'zod';
export const QuoteSchema=z.object({symbol:z.string(),observedAt:z.string().datetime(),receivedAt:z.string().datetime(),priceCents:z.number().int().positive(),currency:z.enum(['KRW','USD']),delayMs:z.number().int().nonnegative(),source:z.string(),raw:z.unknown()});export type NormalizedQuote=z.infer<typeof QuoteSchema>;
export interface RealtimeMarketDataProvider{getQuotes(symbols:string[],now?:Date):Promise<NormalizedQuote[]>}
type Fetch=typeof fetch;type Token={access_token:string;expires_in?:number};
export class TossMarketDataProvider implements RealtimeMarketDataProvider{private token:string|null=null;private expiresAt=0;constructor(private readonly config:{clientId:string;clientSecret:string;baseUrl?:string;fetch?:Fetch}){}private async accessToken(){if(this.token&&Date.now()<this.expiresAt-30_000)return this.token;const body=new URLSearchParams({grant_type:'client_credentials',client_id:this.config.clientId,client_secret:this.config.clientSecret});const response=await(this.config.fetch??fetch)(`${this.config.baseUrl??'https://openapi.tossinvest.com'}/oauth2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error(`Toss OAuth failed: ${response.status}`);const token=await response.json()as Token;this.token=token.access_token;this.expiresAt=Date.now()+(token.expires_in??3600)*1000;return this.token;}async getQuotes(symbols:string[],now=new Date()){if(!symbols.length||symbols.length>200)throw new Error('Toss prices supports 1..200 symbols');const receivedAt=now.toISOString();const response=await(this.config.fetch??fetch)(`${this.config.baseUrl??'https://openapi.tossinvest.com'}/api/v1/prices?symbols=${encodeURIComponent(symbols.join(','))}`,{headers:{authorization:`Bearer ${await this.accessToken()}`,accept:'application/json'}});if(!response.ok)throw new Error(`Toss prices failed: ${response.status}`);const data=await response.json()as{result:Array<{symbol:string;timestamp:string|null;lastPrice:string|number;currency:'KRW'|'USD'}>};return data.result.map(item=>{const observedAt=item.timestamp??receivedAt;return QuoteSchema.parse({symbol:item.symbol,observedAt,receivedAt,priceCents:Math.round(Number(item.lastPrice)*100),currency:item.currency,delayMs:Math.max(0,now.getTime()-new Date(observedAt).getTime()),source:'toss-invest',raw:item});});}}
export function validateFreshness(quote:NormalizedQuote,maximumDelayMs:number){return{fresh:quote.delayMs<=maximumDelayMs,reason:quote.delayMs<=maximumDelayMs?null:`quote_delay_${quote.delayMs}ms_exceeds_${maximumDelayMs}ms`};}
export interface DocumentProvider{collect(identifier:string,asOf:Date):Promise<Array<{url:string;publishedAt:string;receivedAt:string;raw:string}>>}
export class SecFilingProvider implements DocumentProvider{constructor(private readonly config:{userAgent:string;fetch?:Fetch}){}async collect(cik:string,asOf:Date){const response=await(this.config.fetch??fetch)(`https://data.sec.gov/submissions/CIK${cik.padStart(10,'0')}.json`,{headers:{'user-agent':this.config.userAgent,accept:'application/json'}});if(!response.ok)throw new Error(`SEC submissions failed: ${response.status}`);const raw=await response.text();return[{url:`https://data.sec.gov/submissions/CIK${cik.padStart(10,'0')}.json`,publishedAt:asOf.toISOString(),receivedAt:new Date().toISOString(),raw}];}}
export class RssNewsProvider implements DocumentProvider{constructor(private readonly endpoint:(symbol:string)=>string,private readonly fetcher:Fetch=fetch){}async collect(symbol:string,asOf:Date){const url=this.endpoint(symbol);const response=await this.fetcher(url,{headers:{accept:'application/rss+xml, application/xml, text/xml'}});if(!response.ok)throw new Error(`News RSS failed: ${response.status}`);return[{url,publishedAt:asOf.toISOString(),receivedAt:new Date().toISOString(),raw:await response.text()}];}}
export type PositionState='planned'|'submitted'|'partially_filled'|'open'|'partially_exited'|'closed'|'cancelled'|'rejected';export interface PositionSnapshot{id:string;symbol:string;state:PositionState;quantity:number;remainingQuantity:number;entryPriceCents:number;target1Cents:number;target2Cents:number;stopCents:number;openedAt:string;timeStopAt:string;realizedPnlCents:number;version:number}
const transitions:Record<PositionState,PositionState[]>={planned:['submitted','cancelled'],submitted:['partially_filled','open','rejected','cancelled'],partially_filled:['open','cancelled'],open:['partially_exited','closed'],partially_exited:['closed'],closed:[],cancelled:[],rejected:[]};
export class RecoverablePositionManager{constructor(private snapshot:PositionSnapshot){}static recover(value:PositionSnapshot){return new RecoverablePositionManager(structuredClone(value));}current(){return structuredClone(this.snapshot);}transition(next:PositionState){if(!transitions[this.snapshot.state].includes(next))throw new Error(`Invalid transition ${this.snapshot.state} -> ${next}`);this.snapshot={...this.snapshot,state:next,version:this.snapshot.version+1};return this.current();}onQuote(priceCents:number,at:string){if(!['open','partially_exited'].includes(this.snapshot.state))return{action:'none' as const,snapshot:this.current()};if(priceCents<=this.snapshot.stopCents||Date.parse(at)>=Date.parse(this.snapshot.timeStopAt)){this.snapshot={...this.snapshot,state:'closed',realizedPnlCents:this.snapshot.realizedPnlCents+(priceCents-this.snapshot.entryPriceCents)*this.snapshot.remainingQuantity,remainingQuantity:0,version:this.snapshot.version+1};return{action:priceCents<=this.snapshot.stopCents?'stop':'time_stop',snapshot:this.current()};}if(this.snapshot.state==='open'&&priceCents>=this.snapshot.target1Cents){const sold=Math.max(1,Math.floor(this.snapshot.quantity/2));this.snapshot={...this.snapshot,state:'partially_exited',remainingQuantity:this.snapshot.quantity-sold,realizedPnlCents:(priceCents-this.snapshot.entryPriceCents)*sold,version:this.snapshot.version+1};return{action:'partial_target',snapshot:this.current()};}if(priceCents>=this.snapshot.target2Cents){this.snapshot={...this.snapshot,state:'closed',realizedPnlCents:this.snapshot.realizedPnlCents+(priceCents-this.snapshot.entryPriceCents)*this.snapshot.remainingQuantity,remainingQuantity:0,version:this.snapshot.version+1};return{action:'final_target',snapshot:this.current()};}return{action:'none' as const,snapshot:this.current()};}}
export interface AlertSink{send(event:{severity:'info'|'warning'|'critical';code:string;message:string;at:string}):Promise<void>}export class ConsoleAlertSink implements AlertSink{async send(event:{severity:'info'|'warning'|'critical';code:string;message:string;at:string}){console.log(JSON.stringify({event:'operational_alert',...event}));}}
