import { DecisionPanel } from "../components/decision-panel";
import { LineagePanel } from "../components/lineage-panel";
import { ReportView } from "../components/report-view";
import { ScoreCard } from "../components/score-card";
import { StatusBadge } from "../components/status-badge";
import { formatDecimalString } from "../lib/decimal-format";

const nav = ["Home", "Long-term", "Momentum", "Portfolio", "Decisions", "Reports", "Learning", "Operations"];
const mobileNav = [{ label: "Home", href: "#home" }, { label: "Strategies", href: "#long-term" }, { label: "Portfolio", href: "#portfolio" }, { label: "Decisions", href: "#decisions" }, { label: "Reports", href: "#reports" }];

export default function Home() {
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">IO</span><div><strong>Investment OS</strong><small>Decision review</small></div></div><nav aria-label="주요 메뉴">{nav.map((item, index) => <a href={`#${item.toLowerCase()}`} aria-current={index === 0 ? "page" : undefined} key={item}><span aria-hidden="true">{String(index + 1).padStart(2, "0")}</span>{item}{item === "Decisions" && <b>2</b>}</a>)}</nav><div className="sidebar-footer"><StatusBadge status="READ ONLY" tone="info" /><p>자동 주문 비활성</p></div></aside>
    <div className="workspace">
      <header className="topbar"><div><p className="eyebrow">PORTFOLIO · PRIMARY</p><strong>개인 투자 운영체계</strong></div><div className="topbar-meta"><span>KRW</span><span>Asia/Seoul</span><StatusBadge status="DATA HEALTHY" tone="positive" /></div></header>
      <main id="main">
        <section className="hero" id="home"><div><p className="eyebrow">WEDNESDAY · 22 JUL 2026</p><h1>판단보다 먼저,<br /><em>변화와 위험</em>을 봅니다.</h1><p>서로 다른 전략을 섞지 않고, 검증된 결과와 반대 근거를 한 흐름에서 검토합니다.</p></div><div className="hero-status"><span>Data as of</span><strong>2026-07-22 18:00 KST</strong><small>Snapshot 3개 · Model 2개 · Policy 1개</small></div></section>
        <section className="attention" aria-labelledby="attention-title"><div className="section-title"><div><p className="eyebrow">ATTENTION QUEUE</p><h2 id="attention-title">지금 확인할 항목</h2></div><span>우선순위순 3건</span></div><div className="attention-grid"><article className="attention-item critical"><span>01</span><div><StatusBadge status="REVIEW REQUIRED" tone="critical" /><h3>Core Thesis 변화 확인</h3><p>수익성 가정이 약화되었습니다. 점수 변화 설명과 반대 근거를 먼저 확인하세요.</p></div><button aria-label="Core Thesis 변화 검토">검토</button></article><article className="attention-item caution"><span>02</span><div><StatusBadge status="EXPIRING" tone="caution" /><h3>Momentum Plan 만료 임박</h3><p>오늘 21:00 KST 이후 현재 Plan으로 신규 진입할 수 없습니다.</p></div><button aria-label="Momentum Plan 만료 확인">확인</button></article><article className="attention-item info"><span>03</span><div><StatusBadge status="REPORT READY" tone="info" /><h3>주간 Report 생성 완료</h3><p>Canonical Source 6개와 Artifact 3개가 검증되었습니다.</p></div><button aria-label="주간 Report 열기">열기</button></article></div></section>
        <section className="portfolio-strip" id="portfolio" aria-labelledby="portfolio-title"><div><p className="eyebrow">PORTFOLIO SNAPSHOT</p><h2 id="portfolio-title">포트폴리오</h2><small>기준시각 18:00 KST</small></div><div className="portfolio-metric"><span>Investable NAV</span><strong>{formatDecimalString("128450000", { currency: "KRW" })}</strong></div><div className="portfolio-metric"><span>Long-term</span><strong>83.4%</strong><small>정책 80–90%</small></div><div className="portfolio-metric"><span>Momentum</span><strong>11.2%</strong><small>Open risk 0.74%</small></div><div className="portfolio-metric"><span>Cash</span><strong>5.4%</strong><small>유지 사유 있음</small></div></section>
        <section className="strategy-section" aria-labelledby="strategy-title"><div className="section-title"><div><p className="eyebrow">STRATEGIES · INDEPENDENT</p><h2 id="strategy-title">전략별 판단</h2></div><span>점수는 합산하지 않습니다</span></div><div className="score-cards"><ScoreCard title="Core · Hanul Systems" strategy="long-term" score={{ status: "SCORED", score: { point: 82, low: 76, high: 87 }, confidence: { score: 71, grade: "MEDIUM" }, blockerCodes: [], warningCodes: ["THESIS_ASSUMPTION_WEAKENED"] }} /><ScoreCard title="Breakout · Mirae Robotics" strategy="momentum" score={{ status: "BLOCKED", blockerCodes: ["EVENT_GAP_SCENARIO_REQUIRED"], warningCodes: [] }} /></div></section>
        <div className="content-grid"><ReportView title="Weekly Investment OS" status="READY" recommendation="Core Thesis 변화의 근거를 검토하고 신규 자금은 현금으로 유지" dataAsOf="2026-07-22 18:00 KST" sections={[{ kind: "CONCLUSION", heading: "Conclusion", statements: [{ id: "s1", kind: "INTERPRETATION", text: "Portfolio Hard Limit 위반은 없지만 Core 가정 변화가 우선 검토 대상입니다.", sourceIds: ["score-change-21", "portfolio-snapshot-77"] }] }, { kind: "COUNTER_EVIDENCE", heading: "Counter evidence", statements: [{ id: "s2", kind: "FACT", text: "최근 현금흐름과 산업 수요 지표는 기존 가정을 지지합니다.", sourceIds: ["evidence-184"] }] }, { kind: "RISKS", heading: "Risks", statements: [{ id: "s3", kind: "INTERPRETATION", text: "다음 실적 전까지 불확실성 범위가 넓습니다.", sourceIds: ["long-term-evaluation-9"] }] }]} /><div className="right-column"><DecisionPanel decisionId="DEC-2026-0722" contract={{ status: "PENDING_APPROVAL", riskStatus: "ALLOW", stale: false, expiresAt: "2026-07-23T12:00:00Z", now: "2026-07-22T12:00:00Z" }} /><LineagePanel dataAsOf="2026-07-22T09:00:00Z" snapshots={["portfolio-77", "market-219", "fx-31"]} models={["long-term-1.4", "scoring-core-1.2"]} resultHash="79af10e6…d2c9" /></div></div>
      </main>
      <nav className="mobile-nav" aria-label="모바일 주요 메뉴">{mobileNav.map((item) => <a href={item.href} key={item.label}>{item.label}</a>)}</nav>
    </div>
  </div>;
}
